apiVersion: v1 
kind: Service 
metadata:
## same name to be mentioned as application.properties
  name: vprocache01
spec:
  ports:
    - port: 1211
      targetPort: vpromc-port
      protocol: TCP
  selector:
    app: vpromc
  type: ClusterIP