apiVersion: v1
kind: Service 
metadata:
## keep the same as mentioned in application properties 
  name: vpromq01 
spec:
  ports:
    - port: 15672
      targetPort: vpromq01-port 
      protocol: TCP
  selector:
    app: vpromq01 
  type: ClusterIP