apiVersion: apps/v1
kind: Deployment 
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1    
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: sadath17/vprodb:V2
          args:
          ## if we dont do it wunt mount to ebs since it has data not free and it wil have this dir option to map
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: db-pass  

      nodeSelector:
        zone: ap-northeast-1a        
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-0227bcdd26d8e41ab
            fsType: ext4


        
