apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
  selector:
    app: vproapp
    ## because this app is listening from outside so loadbalancer or else if some internal communication was der means it wud be clusterIp
  type: LoadBalancer
